# Generated by Django 4.0.2 on 2022-02-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_view_alter_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view',
            new_name='views',
        ),
    ]
